### PR TITLE
add ChatGPT as translation option

### PR DESCRIPTION
**Pull request by rbenza**

### CODE REVIEW

**Comment by rbenza** [comment]
@Airsaid I still get this error when trying to translate a strings.xml file

```
com.intellij.diagnostic.PluginException: Cannot create class com.airsaid.localization.config.SettingsState (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AndroidLocalize, id=com.github.airsaid.androidlocalize, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\223.8

Caused by: java.lang.NoClassDefFoundError: com/aliyun/teaopenapi/models/Config
	at com.airsaid.localization.translate.impl.ali.AliTranslator.<init>(AliTranslator.java:48)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 75 more
Caused by: java.lang.ClassNotFoundException: com.aliyun.teaopenapi.models.Config PluginClassLoader(plugin=PluginDescriptor(name=AndroidLocalize, id=com.github.airsaid.androidlocalize, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\223.8617.56.2231.9687552.plugins\AndroidLocalizePlugin-3.0.0.jar, version=3.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=137, state=active)
	... 82 more
```

**Comment by Airsaid** [comment]
I don't have that problem on my end, it looks like the corresponding class is not downloaded from the maven repository.

I ran it and found that the OpenAI Icon image is a bit too big, so I will replace it.

**Comment by Airsaid** [comment]
I made some changes, can you see if it's OK now?

**Comment by rbenza** [comment]
> I made some changes, can you see if it's OK now?

Yes, looks fine to me. Can you update and release the new version? I will try your build then. Can't seem to fix this maven issue.

**Comment by rbenza** [comment]
> It's great, I ran the latest version and it works fine.
> 
> Using the infinite timeout I don't think is very good, it does block the currently translated string.
> 
> The timeout issue is usually a problem with the user's network or translation API service, and there is nothing we can do on the plugin side to fix it. Maybe we could set a slightly longer timeout instead of an infinite timeout?
> 
> Also, what is the approximate increase in accuracy after adding system roles to ChatGPT? Because currently, every translation will carry the system role command, which will significantly increase the token usage.

Think the  ChatGPT system role is important to get the best result. It's around 100 tokens so only 0.0002 dollar cent per translated string. If you translate 500 strings this would be 0,10 dollar. That's acceptable to me. Maybe we can shorten it a bit.

However I still often get timeout errors. One thing we should add is at least return all the currently translated strings, before the error happens.. Since now everytime an error occurs all the previously translated strings are not being returned. So you waste money each time a error happens since OpenAI is a paid service.

Another thing that would be great is make the notification dynamic. So 'translation to Italian, sting 2 of 423' that keeps updating so you now you're progress.

**Comment by Airsaid** [comment]
> > It's great, I ran the latest version and it works fine.
> > Using the infinite timeout I don't think is very good, it does block the currently translated string.
> > The timeout issue is usually a problem with the user's network or translation API service, and there is nothing we can do on the plugin side to fix it. Maybe we could set a slightly longer timeout instead of an infinite timeout?
> > Also, what is the approximate increase in accuracy after adding system roles to ChatGPT? Because currently, every translation will carry the system role command, which will significantly increase the token usage.
> 
> Think the ChatGPT system role is important to get the best result. It's around 100 tokens so only 0.0002 dollar per translated string. If you translate 500 strings this would be 0.10 dollar. That's acceptable to me. Maybe we can shorten it a bit.
> 
> However I still often get timeout errors. Can not be my connection since i'm on high end 1gbit/s connection. One thing we should add is at least return all the currently translated strings, before the error happens.. Since now everytime an error occurs all the previously translated strings are not being returned. So you waste money each time a error happens since OpenAI is a paid service.
> 
> Another thing that would be great is make the notification dynamic. So 'translating to Italian... (string 2 of 423)' that keeps updating so you know the current progress.

I've seen the last few commits shorten the command.

The problem of interruption after an error is indeed a big optimization point, I will optimize the logic of this piece in the next few days. 

Also about optimizing the notification content, this is also a good suggestion, I should be able to optimize it in the next version.

I don't think this PR is much of a problem anymore. Is there anything else to optimize on your end? If not, I think it can be merged.

**Comment by rbenza** [comment]
Yes, you can merge the PR. But I would only do a release if you fix the issue that the translated (and paid for) strings are returned when an error occurs.

**Comment by Airsaid** [comment]
I merged it, thanks again for your contribution!

**Pull request merged**
